---
# Allow version tags like @v4, don't require SHA pinning
# Credential persistence is acceptable for checkout in lint workflow
rules:
  unpinned-uses:
    ignore: [ ]
    config:
      policies:
        "*": ref-pin
  artipacked:
    ignore:
      - lint.yml
